"resource/mainmenu.res"
{
	// ==========================================================
	// 基础面板与全局容器
	// ==========================================================
	"BaseGameUIPanel"
	{
		"base_resolution_wide"		"640"
		"base_resolution_tall"		"480"
		"ControlName"		"CBaseModPanel"
		"fieldName"		"BaseGameUIPanel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"1280"
		"tall"		"720"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}

	"GameMenu"
	{
		"base_resolution_wide"		"640"
		"base_resolution_tall"		"480"
		"ControlName"		"CGameMenu"
		"fieldName"		"GameMenu"
		"xpos"		"560"
		"ypos"		"75"
		"zpos"		"1"
		"wide"		"795"
		"tall"		"0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}

	"PlayerModel"
	{
		"fieldName"			"PlayerModel"
		"zpos"				"-4"
		"ypos" "-10"
		"visible"			"1"
		"enabled"			"1"

		"fov"				"42.0"
		"camera_origin"		"117.27 5.7 50.58"
		"camera_angles"		"0.00 -180.00 0.00"
		"lights"
		{
			"ambient_light"	"0.17 0.20 0.26"
			"spot_light_0"
			{
				"position"	"46.28 -8.61 143.56"
				"color"		"0.81 0.92 1.00"
				"lookat"		"0.0 0.0 0.0"
				"inner_cone"	"0.5"
				"outer_cone"	"1.0"
			}
		}
	}

	// ==========================================================
	// 左侧垂直导航栏背景 (1920x1080 基准)
	// ==========================================================
	"left_nvgbar_up1"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"ImagePanel"
		"fieldName"		"left_nvgbar_up1"
		"xpos"		"0"
		"ypos"		"0"
		"zpos"		"0"
		"wide"		"100"
		"tall"		"100"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"FillColor"		"90 90 90 169"
		"scaleImage"		"1"
		"scaleAmount"		"0.000000"
		"tileImage"		"0"
		"tileHorizontally"		"0"
		"tileVertically"		"0"
	}

	"left_nvgbar_up2"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"ImagePanel"
		"fieldName"		"left_nvgbar_up2"
		"xpos"		"0"
		"ypos"		"101"
		"zpos"		"0"
		"wide"		"100"
		"tall"		"200"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"FillColor"		"90 90 90 169"
		"scaleImage"		"1"
		"scaleAmount"		"0.000000"
		"tileImage"		"0"
		"tileHorizontally"		"0"
		"tileVertically"		"0"
	}

	"left_nvgbar_down"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"ImagePanel"
		"fieldName"		"left_nvgbar_down"
		"xpos"		"0"
		"ypos"		"302"
		"zpos"		"0"
		"wide"		"100"
		"tall"		"780"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"FillColor"		"90 90 90 169"
		"scaleImage"		"1"
		"scaleAmount"		"0.000000"
		"tileImage"		"0"
		"tileHorizontally"		"0"
		"tileVertically"		"0"
	}

	// ==========================================================
	// 左侧导航栏功能按钮 (按 Y 轴坐标排序)
	// ==========================================================
	"left_top_logo"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"Button"
		"fieldName"		"left_top_logo"
		"xpos"		"0"
		"ypos"		"0"
		"zpos"		"1"
		"wide"		"100"
		"tall"		"100"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"b"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"GameMenuFont2"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}

	"playbtn"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"Button"
		"fieldName"		"playbtn"
		"xpos"		"0"
		"ypos"		"100"
		"tooltiptext"		"Play offline with bots"
		"zpos"		"1"
		"wide"		"100"
		"tall"		"100"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"c"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"GameMenuFont2"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"OpenCreateMultiplayerGameDialog"
		"Default"		"0"
		"sound_released"	"UI/buttonclick5.wav"
		"sound_armed"		"UI/buttonrollover.wav"
	}

	"openserversbtn"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"Button"
		"fieldName"		"openserversbtn"
		"xpos"		"0"
		"ypos"		"200"
		"tooltiptext"		"Source Offensive Mod-options"
		"zpos"		"0"
		"wide"		"100"
		"tall"		"100"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"["
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"GameMenuFontD"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command" "OpenServerBrowser"
		"Default"		"0"
		"sound_released"	"UI/buttonclick.wav"
		"sound_armed"		"UI/buttonrollover.wav"
	}

	"modoptionsbtn"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"Button"
		"fieldName"		"modoptionsbtn"
		"xpos"		"0"
		"ypos"		"300"
		"tooltiptext"		"Source Offensive Mod-options"
		"zpos"		"0"
		"wide"		"100"
		"tall"		"100"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"k"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"GameMenuFont2"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"OpenModOptionsDialog"
		"Default"		"0"
		"sound_released"	"UI/buttonclick4.wav"
		"sound_armed"		"UI/buttonrollover.wav"
	}

	"demobtn"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"Button"
		"fieldName"		"demobtn"
		"xpos"		"0"
		"ypos"		"400"
		"tooltiptext"		"demo viewer"
		"zpos"		"1"
		"wide"		"100"
		"tall"		"100"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"h"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"GameMenuFont2"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"engine demoui"
		"Default"		"0"
		"sound_released"	"UI/buttonclick6.wav"
		"sound_armed"		"UI/buttonrollover.wav"
	}

	"settingsbtn"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"Button"
		"fieldName"		"settingsbtn"
		"xpos"		"0"
		"ypos"		"600"
		"tooltiptext"		"setiings"
		"zpos"		"1"
		"wide"		"100"
		"tall"		"100"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"e"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"GameMenuFont2"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"OpenOptionsDialog"
		"Default"		"0"
		"sound_released"	"UI/buttonclick3.wav"
		"sound_armed"		"UI/buttonrollover.wav"
	}

	"quitbtn"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"Button"
		"fieldName"		"quitbtn"
		"xpos"		"0"
		"ypos"		"980"
		"tooltiptext"		"exit to desktop"
		"zpos"		"1"
		"wide"		"100"
		"tall"		"100"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"d"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"GameMenuFont2"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"QUIT"
		"Default"		"0"
		"sound_released"	"UI/buttonclick7.wav"
		"sound_armed"		"UI/buttonrollover.wav"
	}

	// ==========================================================
	// 旧版基准 (640x480) 按钮控件
	// ==========================================================
	"GameMenuButton"
	{
		"base_resolution_wide"		"640"
		"base_resolution_tall"		"480"
		"ControlName"		"Button"
		"fieldName"		"GameMenuButton"
		"xpos"		"42"
		"ypos"		"140"
		"wide"		"289"
		"tall"		"65"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"COUNTER-STRIKE'"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"OpenGameMenu"
		"Default"		"0"
	}

	"GameMenuButton2"
	{
		"base_resolution_wide"		"640"
		"base_resolution_tall"		"480"
		"ControlName"		"Button"
		"fieldName"		"GameMenuButton2"
		"xpos"		"506"
		"ypos"		"30"
		"wide"		"224"
		"tall"		"41"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Source Offensive"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"OpenGameMenu"
		"Default"		"0"
	}

	// ==========================================================
	// 中央/右侧 信息面板 (新闻与皮肤预览区)
	// ==========================================================
	"right_news_panel"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"ImagePanel"
		"fieldName"		"right_news_panel"
		"xpos"		"150"
		"ypos"		"30"
		"zpos"		"0"
		"wide"		"800"
		"tall"		"800"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"FillColor"		"90 90 90 169"
		"scaleImage"		"1"
		"scaleAmount"		"0.000000"
		"tileImage"		"0"
		"tileHorizontally"		"0"
		"tileVertically"		"0"
	}

	"left_skinview_panel"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"ImagePanel"
		"fieldName"		"left_skinview_panel"
		"xpos"		"150"
		"ypos"		"850"
		"zpos"		"0"
		"wide"		"800"
		"tall"		"270"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"FillColor"		"90 90 90 169"
		"scaleImage"		"1"
		"scaleAmount"		"0.000000"
		"tileImage"		"0"
		"tileHorizontally"		"0"
		"tileVertically"		"0"
	}

	// ==========================================================
	// 屏幕右侧导航栏/ (xpos=2240)
	// ==========================================================
	"right_nvgbar_top"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"ImagePanel"
		"fieldName"		"right_nvgbar_top"
		"xpos"		"2240"
		"ypos"		"0"
		"zpos"		"0"
		"wide"		"100"
		"tall"		"100"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"FillColor"		"90 90 90 169"
		"scaleImage"		"1"
		"scaleAmount"		"0.000000"
		"tileImage"		"0"
		"tileHorizontally"		"0"
		"tileVertically"		"0"
	}
	
	"right_nvgbar_avatarview"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"right_nvgbar_avatarview"
		"xpos"		"1000"
		"ypos"		"5"
		"wide"		"35"
		"tall"		"35"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"1 row"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"scaleImage"		"1"
		"image"			"hud\tx"
	}

	"rightbar_openachievement"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"Button"
		"fieldName"		"openachievement_dialog"
		"xpos"		"2240"
		"ypos"		"100"
		"tooltiptext"		"demo viewer"
		"zpos"		"1"
		"wide"		"100"
		"tall"		"100"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"g"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Font"		"GameMenuFontD"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"OpenCSAchievementsDialog"
		"Default"		"0"
		"sound_released"	"UI/buttonclick8.wav"
		"sound_armed"		"UI/buttonclick8.wav"
	}

	"right_nvgbar_down"
	{
		"base_resolution_wide"		"1920"
		"base_resolution_tall"		"1080"
		"ControlName"		"ImagePanel"
		"fieldName"		"right_nvgbar_down"
		"xpos"		"2240"
		"ypos"		"102"
		"zpos"		"0"
		"wide"		"100"
		"tall"		"980"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"FillColor"		"90 90 90 169"
		"scaleImage"		"1"
		"scaleAmount"		"0.000000"
		"tileImage"		"0"
		"tileHorizontally"		"0"
		"tileVertically"		"0"
	}
}