"Resource/ModOptionsSubKnives.res"
{
	"ModOptionsSubKnives"
	{
		"ControlName"		"CModOptionsSubKnives"
		"fieldName"		"ModOptionsSubKnives"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"496"
		"tall"		"314"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"fieldName"		"Cancel"
		"xpos"		"810"
		"ypos"		"612"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"3"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Cancel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"Close"
		"Default"		"0"
	}
	"ok"
	{
		"ControlName"		"Button"
		"fieldName"		"OK"
		"xpos"		"740"
		"ypos"		"612"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"3"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_OK"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"Ok"
		"Default"		"0"
	}
	"Apply"
	{
		"ControlName"		"Button"
		"fieldName"		"Apply"
		"xpos"		"880"
		"ypos"		"612"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"3"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Apply"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"Apply"
		"Default"		"0"
	}
	"KnifeImageCT"
	{
		"ControlName"		"Panel"
		"fieldName"		"KnifeImageCT"
		"xpos"		"16"
		"ypos"		"32"
		"wide"		"224"
		"tall"		"168"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"KnifeImageT"
	{
		"ControlName"		"Panel"
		"fieldName"		"KnifeImageT"
		"xpos"		"256"
		"ypos"		"32"
		"wide"		"224"
		"tall"		"168"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"KnifeCTComboBoxLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"KnifeCTComboBoxLabel"
		"xpos"		"16"
		"ypos"		"8"
		"wide"		"224"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Loadout_Knife_CT"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"KnifeCTComboBox"
	{
		"ControlName"		"CLabeledCommandComboBox"
		"fieldName"		"KnifeCTComboBox"
		"xpos"		"16"
		"ypos"		"216"
		"wide"		"224"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"KnifeTComboBoxLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"KnifeTComboBoxLabel"
		"xpos"		"256"
		"ypos"		"8"
		"wide"		"224"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Loadout_Knife_T"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"KnifeTComboBox"
	{
		"ControlName"		"CLabeledCommandComboBox"
		"fieldName"		"KnifeTComboBox"
		"xpos"		"256"
		"ypos"		"216"
		"wide"		"224"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"SysMenu"
	{
		"ControlName"		"Menu"
		"fieldName"		"SysMenu"
		"xpos"		"0"
		"ypos"		"0"
		"zpos"		"1"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
	}
}
