"Resource/ModOptionsSubGameplay.res"
{
	"ModOptionsSubGameplay"
	{
		"ControlName"		"CModOptionsSubGameplay"
		"fieldName"		"ModOptionsSubGameplay"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"496"
		"tall"		"314"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"fieldName"		"Cancel"
		"xpos"		"810"
		"ypos"		"612"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"3"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Cancel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"Close"
		"Default"		"0"
	}
	"ok"
	{
		"ControlName"		"Button"
		"fieldName"		"OK"
		"xpos"		"740"
		"ypos"		"612"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"3"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_OK"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"Ok"
		"Default"		"0"
	}
	"Apply"
	{
		"ControlName"		"Button"
		"fieldName"		"Apply"
		"xpos"		"880"
		"ypos"		"612"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"3"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Apply"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"Apply"
		"Default"		"0"
	}
	"ViewmodelLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ViewmodelLabel"
		"xpos"		"16"
		"ypos"		"0"
		"wide"		"192"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gameplay_Viewmodel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"ViewmodelOffsetXSlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"ViewmodelOffsetXSlider"
		"xpos"		"24"
		"ypos"		"24"
		"wide"		"128"
		"tall"		"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"leftText"		"#GameUI_Left"
		"rightText"		"#GameUI_Right"
	}
	"ViewmodelOffsetXLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ViewmodelOffsetXLabel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_to_sibling"		"ViewmodelOffsetXSlider"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"ViewmodelOffsetYSlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"ViewmodelOffsetYSlider"
		"xpos"		"24"
		"ypos"		"60"
		"wide"		"128"
		"tall"		"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"leftText"		"#GameUI_Backward"
		"rightText"		"#GameUI_Forward"
	}
	"ViewmodelOffsetYLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ViewmodelOffsetYLabel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_to_sibling"		"ViewmodelOffsetYSlider"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"ViewmodelOffsetZSlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"ViewmodelOffsetZSlider"
		"xpos"		"24"
		"ypos"		"96"
		"wide"		"128"
		"tall"		"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"leftText"		"#GameUI_Down"
		"rightText"		"#GameUI_Up"
	}
	"ViewmodelOffsetZLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ViewmodelOffsetZLabel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_to_sibling"		"ViewmodelOffsetZSlider"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"ViewmodelOffsetPresetLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ViewmodelOffsetPresetLabel"
		"xpos"		"352"
		"ypos"		"0"
		"wide"		"192"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gameplay_ViewmodelPreset"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"ViewmodelOffsetPreset"
	{
		"ControlName"		"CLabeledCommandComboBox"
		"fieldName"		"ViewmodelOffsetPreset"
		"xpos"		"352"
		"ypos"		"24"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ViewmodelFOVDescription"
	{
		"ControlName"		"Label"
		"fieldName"		"ViewmodelFOVDescription"
		"xpos"		"184"
		"ypos"		"0"
		"wide"		"192"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gameplay_ViewmodelFOV"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"ViewmodelFOVSlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"ViewmodelFOVSlider"
		"xpos"		"184"
		"ypos"		"24"
		"wide"		"128"
		"tall"		"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"leftText"		"#GameUI_Smaller"
		"rightText"		"#GameUI_Bigger"
	}
	"ViewmodelFOVLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ViewmodelFOVLabel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_to_sibling"		"ViewmodelFOVSlider"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"ViewmodelRecoilDescription"
	{
		"ControlName"		"Label"
		"fieldName"		"ViewmodelRecoilDescription"
		"xpos"		"184"
		"ypos"		"72"
		"wide"		"192"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gameplay_ViewmodelRecoil"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"tooltiptext"	"#GameUI_Gameplay_ViewmodelRecoil_Hint"
	}
	"ViewmodelRecoilSlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"ViewmodelRecoilSlider"
		"xpos"		"184"
		"ypos"		"96"
		"wide"		"128"
		"tall"		"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"leftText"		"#GameUI_Smaller"
		"rightText"		"#GameUI_Bigger"
		"tooltiptext"	"#GameUI_Gameplay_ViewmodelRecoil_Hint"
	}
	"ViewmodelRecoilLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ViewmodelRecoilLabel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_to_sibling"		"ViewmodelRecoilSlider"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"ViewbobStyleLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ViewbobStyleLabel"
		"xpos"		"352"
		"ypos"		"48"
		"wide"		"192"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gameplay_ViewbobStyle"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"ViewbobStyleComboBox"
	{
		"ControlName"		"CLabeledCommandComboBox"
		"fieldName"		"ViewbobStyleComboBox"
		"xpos"		"352"
		"ypos"		"72"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"WeaponPositionLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"WeaponPositionLabel"
		"xpos"		"352"
		"ypos"		"96"
		"wide"		"192"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gameplay_WeaponPos"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"WeaponPositionComboBox"
	{
		"ControlName"		"CLabeledCommandComboBox"
		"fieldName"		"WeaponPositionComboBox"
		"xpos"		"352"
		"ypos"		"120"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider1"
		"xpos"		"16"
		"ypos"		"152"
		"wide"		"464"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"CloseOnBuyCheckbox"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"CloseOnBuyCheckbox"
		"xpos"		"16"
		"ypos"		"162"
		"wide"		"464"
		"tall"		"24"
		"autoResize"		"1"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gameplay_CloseOnBuy"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"UseOpensBuyMenuCheckbox"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"UseOpensBuyMenuCheckbox"
		"xpos"		"16"
		"ypos"		"186"
		"wide"		"464"
		"tall"		"24"
		"autoResize"		"1"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gameplay_UseOpensBuyMenu"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"AddBotPrefix"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"AddBotPrefix"
		"xpos"		"16"
		"ypos"		"210"
		"wide"		"464"
		"tall"		"24"
		"autoResize"		"1"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gameplay_AddBotPrefix"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"DrawTracers"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"DrawTracers"
		"xpos"		"16"
		"ypos"		"234"
		"wide"		"464"
		"tall"		"24"
		"autoResize"		"1"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gameplay_DrawTracers"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"SpecInterpCamera"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"SpecInterpCamera"
		"xpos"		"16"
		"ypos"		"258"
		"wide"		"464"
		"tall"		"24"
		"autoResize"		"1"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gameplay_SpecInterpCamera"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
		"tooltiptext"	"#GameUI_Gameplay_SpecInterpCamera_Hint"
	}
	"DisableShootingEffects"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"DisableShootingEffects"
		"xpos"		"16"
		"ypos"		"282"
		"wide"		"464"
		"tall"		"24"
		"autoResize"		"1"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gameplay_DisableShootingEffects"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
		"tooltiptext"	"#GameUI_Gameplay_DisableShootingEffects_Hint"
	}
	"SysMenu"
	{
		"ControlName"		"Menu"
		"fieldName"		"SysMenu"
		"xpos"		"0"
		"ypos"		"0"
		"zpos"		"1"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
	}
}
