#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'GameUI'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('GAMEUI_EXPORTS',1)
	conf.define('NO_STEAM',1)
	conf.define('VERSION_SAFE_STEAM_API_INTERFACES',1)

def build(bld):
	source = [
		'BackgroundMenuButton.cpp',
		'BasePanel.cpp',
		'CustomMenu.cpp',
		'GameConsole.cpp',
		'GameUI_Interface.cpp',
		'ModInfo.cpp',
		'MouseMessageForwardingPanel.cpp',
		'../common/GameUI/ObjectList.cpp',
		'PanelListPanel.cpp',
		'RunGameEngine.cpp',
		'../common/GameUI/scriptobject.cpp',
		'Sys_Utils.cpp',
		'TextEntryBox.cpp',
		'TGAImagePanel.cpp',
		'../public/vgui_controls/vgui_controls.cpp',
		'VGuiSystemModuleLoader.cpp',
		'BonusMapsDatabase.cpp',
		'../common/language.cpp',
		'../common/imageutils.cpp',
		'GameDialogs/SaveGameBrowserDialog.cpp',
		'gameui_util.cpp',
		'BitmapImagePanel.cpp',
		'CommandCheckButton.cpp',
		'CvarNegateCheckButton.cpp',
		'../common/GameUI/cvarslider.cpp',
		'CvarTextEntry.cpp',
		'CvarToggleCheckButton.cpp',
		'HapticControlBox.cpp',
		'KeyToggleCheckButton.cpp',
		'LabeledCommandComboBox.cpp',
		'URLButton.cpp',
		'vcontrolslistpanel.cpp',
		'BenchmarkDialog.cpp',
		'BonusMapsDialog.cpp',
		'CommentaryDialog.cpp',
		'CommentaryExplanationDialog.cpp',
		'ContentControlDialog.cpp',
		'CustomTabExplanationDialog.cpp',
		'GameConsoleDialog.cpp',
		'GameDialogs/LoadGameDialog.cpp',
		'MultiplayerAdvancedDialog.cpp',
		'GameDialogs/NewGameDialog.cpp',
		'GameDialogs/PlayerListDialog.cpp',
		'GameDialogs/SaveGameDialog.cpp',
		'GameDialogs/LoadCommentaryDialog.cpp',
		'GameDialogs/LoadingDialog.cpp',
		'BaseSaveGameDialog.cpp',
		'GameDialogs/CreateMultiplayerGameBotPage.cpp',
		'GameDialogs/CreateMultiplayerGameDialog.cpp',
		'GameDialogs/CreateMultiplayerGameGameplayPage.cpp',
		'GameDialogs/CreateMultiplayerGameServerPage.cpp',
		'matchmaking/achievementsdialog.cpp',
		'matchmaking/basedialog.cpp',
		'matchmaking/dialogmenu.cpp',
		'matchmaking/leaderboarddialog.cpp',
		'matchmaking/matchmakingbasepanel.cpp',
		'matchmaking/pausedialog.cpp',
		'matchmaking/sessionlobbydialog.cpp',
		'matchmaking/sessionoptionsdialog.cpp',
		'matchmaking/sessionbrowserdialog.cpp',
		'matchmaking/welcomedialog.cpp',
		'OptionsDialog/OptionsDialog.cpp',
		'OptionsDialog/OptionsSubAudio.cpp',
		'OptionsDialog/OptionsSubGame.cpp',
		'OptionsDialog/OptionsSubKeyboard.cpp',
		'OptionsDialog/OptionsSubMouse.cpp',
		'OptionsDialog/OptionsSubTouch.cpp',
		'OptionsDialog/OptionsSubMultiplayer.cpp',
		'OptionsDialog/OptionsSubVideo.cpp',
		'OptionsDialog/OptionsSubVoice.cpp',
		'GameDialogs/ExtraManagerPanel.cpp',
		'../public/tier0/memoverride.cpp',
		'ModSettingsDialog/ModOptionsDialog.cpp',
		'ModSettingsDialog/ModOptionsSubCrosshair.cpp',
		'ModSettingsDialog/ModOptionsSubLoadout.cpp',
		'ModSettingsDialog/ModOptionsSubGameplay.cpp',
		'ModSettingsDialog/ModOptionsSubKnives.cpp',
		'ModSettingsDialog/ModOptionsSubAgents.cpp',
		'ModSettingsDialog/ModOptionsSubGloves.cpp',
		'ModSettingsDialog/ModOptionsSubHUD.cpp',
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'LogoFile.cpp',
			'ChangeGameDialog.cpp',
			'OptionsDialog/OptionsSubHaptics.cpp'
		]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common',
		'../common/GameUI',
		'../game/client',
		'../game/shared',
		'../game/shared/cstrike',
		'../thirdparty'
	]

	defines = []

	libs = ['tier0','vgui_controls','tier1','tier2','tier3','vstdlib','vtf','bitmap','mathlib','SDL2','steam_api','matsys_controls','JPEG','PNG','ZLIB', 'lunasvg']

	if bld.env.DEST_OS == 'win32':
		libs += ['USER32', 'GDI32']
		
	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

